concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}
jobs:
  build:
    secrets:
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      ossrh_token: ${{ secrets.OSSRH_TOKEN }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
    uses: openrewrite/gh-automation/.github/workflows/ci-gradle.yml@main
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
