jobs:
  dependency-submission:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: .*[Tt]est(Compile|Runtime)Classpath
        DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: :buildSrc
      name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
name: Dependency Submission
on:
  repository_dispatch:
    types: trigger-ga___dependency-submission.yml
permissions:
  contents: write
