concurrency:
  cancel-in-progress: false
  group: publish-${{ github.ref }}
jobs:
  release:
    secrets:
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      ossrh_token: ${{ secrets.OSSRH_TOKEN }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
    uses: openrewrite/gh-automation/.github/workflows/publish-gradle.yml@main
name: publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
