concurrency:
  cancel-in-progress: false
  group: backup-${{ github.ref }}
jobs:
  repository-backup:
    secrets:
      bucket_access_key_id: ${{ secrets.S3_GITHUB_REPOSITORY_BACKUPS_ACCESS_KEY_ID
        }}
      bucket_mirror_target: ${{ secrets.S3_GITHUB_REPOSITORY_BACKUPS_BUCKET_NAME }}
      bucket_secret_access_key: ${{ secrets.S3_GITHUB_REPOSITORY_BACKUPS_SECRET_ACCESS_KEY
        }}
    uses: openrewrite/gh-automation/.github/workflows/repository-backup.yml@main
name: repository-backup
on:
  repository_dispatch:
    types: trigger-ga___repository-backup.yml
